bmcIP: "172.16.100.12"
bmcPort: 443
bmcScheme: https
username: admin
password: password
firmwareVersion: "1.0.0"
biosVersion: "1.0.0"
01-bmc-registration:
  model: "Standard PC (Q35 + ICH9, 2009)"
  powerState: "On"
06-biossettings-noreboot:
  key: "AdminPhone"
  value: "+1-555-0100"
  baselineValue: "+1-555-0199"
07-biossettings-reboot:
  key: "BootMode"
  value: "Bios"
  baselineValue: "Uefi"
08-bmcsettings:
  key: "EmailAlert.1.Address"
  value: "alerts@example.com"
  baselineValue: "compat-base@example.com"
