apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/ironcore-dev/metal-maintenance-operator//config/default?ref=f06fc4d9511092f15163a5f8014763d60c615eca

patches:
- path: manager_patch.yaml

images:
- name: controller
  newName: ghcr.io/ironcore-dev/metal-maintenance-operator-controller-manager
  newTag: sha-1b394ae
